In [60]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

from sklearn import decomposition as dec
from sklearn import manifold as man

LATENT SEMANTIC ANALYSIS APPROACH BY USING SVD

In [61]:
data = pd.read_csv("train.csv")
data.head()

userID  movieID  rating
0    4490     2109       4
1    5839     3471       4
2    5382      150       3
3    1262     1237       5
4    6005     2273       4

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990209 entries, 0 to 990208
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userID   990209 non-null  int64
 1   movieID  990209 non-null  int64
 2   rating   990209 non-null  int64
dtypes: int64(3)
memory usage: 22.7 MB


In [63]:
U_matrix = data.pivot("userID", "movieID", "rating")
U_matrix.head()

movieID  1     2     3     4     5     6     ...  3947  3948  3949  3950  3951  3952
userID                                       ...                                    
1         3.0   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
4         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
5         NaN   NaN   NaN   NaN   NaN   3.0  ...   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 3705 columns]

In [64]:
U_matrix_norm = U_matrix - U_matrix.mean(axis=1).values.reshape(-1,1)
U_matrix_norm.fillna(0, inplace=True)
U_matrix_norm.head()

movieID      1     2     3     4     5     ...  3948  3949  3950  3951  3952
userID                                     ...                              
1       -0.571429   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
2        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
3        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
4        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
5        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0

[5 rows x 3705 columns]

In [65]:
m = 500
train = U_matrix_norm[:m]
test = U_matrix_norm[m:]

In [66]:
train_mean = train.mean(axis=0)
centered_train = train - train_mean
centered_train.shape

(500, 3705)

In [67]:
U, S, VT = np.linalg.svd(centered_train.T, full_matrices=False)

In [68]:
print("U shape:", U.shape)
print("S shape:", S.shape)
print("VT shape:", VT.shape)
print("train shape:", centered_train.shape)

U shape: (3705, 500)
S shape: (500,)
VT shape: (500, 500)
train shape: (500, 3705)


In [69]:
np.set_printoptions(suppress=True)

squares = np.array(list(map(lambda x:x**2, S)))
total = squares.sum()

for i in range(1, len(squares)):
  r = squares[:i].sum() / total
  print(i, r)


1 0.06201802352161716
2 0.08570568351700797
3 0.10486912669989941
4 0.12298092272188253
5 0.1390557094847002
6 0.15356343874755032
7 0.16761179692382808
8 0.18096975277730112
9 0.1932579591434031
10 0.2050140342062476
11 0.2164556099621683
12 0.22749320615847252
13 0.23797115911694394
14 0.2478264483212955
15 0.2572043394952447
16 0.266222197030011
17 0.2749436637164614
18 0.28351864793209625
19 0.29181104019051674
20 0.30003109864412614
21 0.3079526046610479
22 0.3156320817857055
23 0.3232078052586004
24 0.33075355938497497
25 0.33800536501226025
26 0.3452211813939935
27 0.3523403763760801
28 0.35906159342420196
29 0.3656786244922367
30 0.3721723287895439
31 0.3786007785782347
32 0.3848442792812918
33 0.39099117952647916
34 0.39699364809316456
35 0.402883094385904
36 0.4087201024894047
37 0.4144501221822523
38 0.42013280209694276
39 0.4256704232463657
40 0.4311329258174505
41 0.4364972708164447
42 0.44178565895465843
43 0.4470153648998907
44 0.45219524795907035
45 0.45730803517959534


In [70]:
k = 236
U = U[:, :k]
S = S[:k]
VT = VT[:k, :]

print("U shape:", U.shape)
print("S shape:", S.shape)
print("VT shape:", VT.shape)
print("train shape:", centered_train.shape)

U shape: (3705, 236)
S shape: (236,)
VT shape: (236, 500)
train shape: (500, 3705)


In [71]:
svd = dec.TruncatedSVD(n_components=200)
temp = svd.fit_transform(centered_train)
temp.shape

(500, 200)

In [72]:
np.diag(S).dot(VT).T

array([[ 1.30600738, -4.21377897,  2.89243998, ...,  0.21995789,
         0.03495619,  0.07027347],
       [-1.24163098,  0.11216455, -0.21010467, ..., -0.47399513,
         0.48883084,  0.21587764],
       [-1.80986896,  0.11608378, -0.31789501, ..., -0.0161422 ,
         0.21539027,  0.34730197],
       ...,
       [ 1.73034949,  0.80204759, -0.1362651 , ..., -0.49524668,
        -0.24620562,  0.15734025],
       [-1.5636002 ,  0.19160636, -0.18823361, ..., -0.16821832,
         0.21418156,  0.06921319],
       [-1.59345654,  0.13976808, -0.35995461, ...,  0.01587169,
        -0.0790654 , -0.07423603]])

In [73]:
U_norm = U / np.linalg.norm(U, axis=1).reshape(-1,1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [74]:
U_norm

array([[ 0.10678396,  0.0046128 , -0.00380119, ...,  0.0462689 ,
        -0.0068094 , -0.06736973],
       [-0.0384543 , -0.05569495, -0.06355138, ...,  0.00928543,
        -0.02151196,  0.01216102],
       [-0.05122112,  0.00872742, -0.05951023, ..., -0.0105522 ,
        -0.0083863 , -0.00163742],
       ...,
       [ 0.00796039,  0.02089689, -0.00051006, ...,  0.01934112,
        -0.1085201 ,  0.05657562],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [-0.00397628, -0.00241113, -0.00187409, ..., -0.04408412,
         0.0505652 , -0.03529741]])

In [75]:
sims = U_norm.dot(U_norm.T)
sims.shape

(3705, 3705)

In [76]:
a = np.isnan(sims)
sims[a] = -1
sims[:3]

array([[ 1.        , -0.02234756,  0.0655853 , ..., -0.08128713,
        -1.        , -0.00809343],
       [-0.02234756,  1.        ,  0.04865898, ..., -0.03452322,
        -1.        ,  0.04919964],
       [ 0.0655853 ,  0.04865898,  1.        , ...,  0.04801145,
        -1.        , -0.00037848]])

In [77]:
data.movieID.value_counts()

2858    3393
1196    2966
260     2963
1210    2854
480     2643
        ... 
1764       1
1118       1
2277       1
1630       1
792        1
Name: movieID, Length: 3705, dtype: int64

In [78]:
data.movieID.value_counts()[:20]

2858    3393
1196    2966
260     2963
1210    2854
480     2643
589     2629
2028    2626
2571    2564
1270    2562
593     2546
1580    2509
608     2492
1198    2482
2762    2437
110     2411
2396    2344
1197    2295
527     2282
1617    2271
1265    2252
Name: movieID, dtype: int64

In [79]:
movieID = 2858
simIndices = sims[movieID].argsort()[::-1][:50]
simIndices

array([2858, 1998, 1519, 2376, 2103, 1557, 3562, 3659, 1324,  898, 1968,
       2154, 3286, 1495, 1198, 2101,  566,  605, 1950,  620,  430, 1136,
       1932, 2976, 1752, 2148, 1850, 1996, 2363,  230, 2177, 2644,  444,
        705, 2147,  845,  503,  728,  917, 1916,  652, 1716, 2324, 2536,
       3338, 3579, 2747, 3181, 1463,  283])

In [80]:
myPreds = []
realLabels = []

for userId in test.index:
  print(userId)
  if userId == 510:
    break
  for movieId in test.columns:
    if not np.isnan(test.loc[userId, movieId]):
      new_user = test.loc[userId:userId, :]
      new_user_center = new_user - train_mean
      new_user_red = svd.transform(new_user_center)
      idx=list(test.columns).index(movieId)
      diff=new_user_red.dot(svd.components_.T[idx])
      user = test.dropna(subset=[userId],axis=1)
      avg=user.loc[userId:userId, :].mean(axis=1).squeeze()
      rate=int(diff)+int(avg)
      myPreds.append(rate)

      real_label = test.loc[userId, movieId]
      realLabels.append(real_label)


501
502
503
504
505
506
507
508
509
510


Finding RMSE Score 

In [81]:
met.mean_squared_error(realLabels, myPreds, squared=False)

0.21409615544298638

Prediction with SVD 

In [48]:
test = pd.read_csv("test_without_labels.csv")
test.head()

IDs
0   629_2683
1    601_904
2  5673_3717
3  5616_1721
4  1099_3697

In [49]:
x = pd.DataFrame(test.IDs.str.split('_',1).tolist(),
                         columns = ['userId','movieId'])
print(x)

     userId movieId
0       629    2683
1       601     904
2      5673    3717
3      5616    1721
4      1099    3697
...     ...     ...
9994   4198    3671
9995    566    3148
9996   5531    2105
9997   4650     377
9998   4919    2094

[9999 rows x 2 columns]


In [50]:
df_test = pd.DataFrame(x)
df_test

userId movieId
0       629    2683
1       601     904
2      5673    3717
3      5616    1721
4      1099    3697
...     ...     ...
9994   4198    3671
9995    566    3148
9996   5531    2105
9997   4650     377
9998   4919    2094

[9999 rows x 2 columns]

In [46]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   userId   9999 non-null   int64
 1   movieId  9999 non-null   int64
dtypes: int64(2)
memory usage: 156.4 KB


In [36]:
U_matrix_norm_mean = U_matrix_norm.mean(axis=0)
centered_U_matrix_ = U_matrix_norm - U_matrix_norm_mean
centered_U_matrix_.shape

(6040, 3705)

In [37]:
U, S, VT = np.linalg.svd(centered_U_matrix_.T, full_matrices=False)
print("U shape:", U.shape)
print("S shape:", S.shape)
print("VT shape:", VT.shape)
print("train shape:", centered_U_matrix_.shape)

U shape: (3705, 3705)
S shape: (3705,)
VT shape: (3705, 6040)
train shape: (6040, 3705)


In [38]:
np.set_printoptions(suppress=True)
squares = np.array(list(map(lambda x:x**2, S)))
total = squares.sum()

for i in range(1, len(squares)):
  r = squares[:i].sum() / total
  print(i, r)

1 0.04332112330675665
2 0.05965703547893181
3 0.06934914720481164
4 0.0777330066728598
5 0.08509410027278207
6 0.09184034287126001
7 0.09758919661114303
8 0.10279816434588687
9 0.10748802776970129
10 0.11194008961848126
11 0.1162291711159264
12 0.12023638271631751
13 0.12405456529853613
14 0.12778421943370724
15 0.13132918046358003
16 0.1347417779914751
17 0.13809517818471717
18 0.14135286375357145
19 0.14448367874072515
20 0.14755639467504267
21 0.1505396736271173
22 0.15343971426244868
23 0.15626935249150714
24 0.15908563760577993
25 0.16183188110655952
26 0.16454822708717065
27 0.16723140762887706
28 0.16986741629733107
29 0.172473273733813
30 0.17504086349866493
31 0.17758429118426822
32 0.18012618068632577
33 0.1826236155391874
34 0.18509376149681628
35 0.18753819899304966
36 0.18995533920729823
37 0.1923483280235701
38 0.19470960891556266
39 0.19705816212541066
40 0.19938350094460672
41 0.20168387515536604
42 0.20397635705611747
43 0.20624104131929072
44 0.20849523953165341
45 0.

In [39]:
k = 1096

U = U[:, :k]
S = S[:k]
VT = VT[:k, :]

print("U shape:", U.shape)
print("S shape:", S.shape)
print("VT shape:", VT.shape)
print("train shape:", centered_U_matrix_.shape)

U shape: (3705, 1096)
S shape: (1096,)
VT shape: (1096, 6040)
train shape: (6040, 3705)


In [40]:
svd = dec.TruncatedSVD(n_components=1096)
temp = svd.fit_transform(centered_U_matrix_)
temp.shape

(6040, 1096)

In [53]:
myPreds = []
for i in range(len(df_test)):
  userId= int(df_test.userId[i])
  movieId= int(df_test.movieId[i])
  new_user = centered_U_matrix_.loc[userId:userId, :]
  new_user_center = new_user - U_matrix_norm_mean
  new_user_red = svd.transform(new_user_center)

  idx=list(centered_U_matrix_.columns).index(movieId)
  diff=new_user_red.dot(svd.components_.T[idx])
  user = U_matrix.dropna(subset=[userId],axis=1)
  avg=user.loc[userId:userId, :].mean(axis=1).squeeze()
  
  rate=diff+avg
  rate=float(rate)
  myPreds.append(rate)

In [54]:
len(myPreds)

9999

In [55]:
test2 = test.copy()
test2["rating"]= myPreds

In [56]:
test2.head()

IDs    rating
0   629_2683  3.926008
1    601_904  4.106348
2  5673_3717  4.003274
3  5616_1721  3.719995
4  1099_3697  3.826879

In [57]:
from google.colab import files
test2.to_csv('submission4_v2.csv',index=False) 
files.download('submission4_v2.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>